_target_: protenix.data.pair_dataset.DataModule
num_workers: 16
pin_memory: True
batch_size: 32
prefetch_factor: 2
dataset_args:
  train:
    _target_: protenix.data.pair_dataset.FullPairDataset
    meta_path: /data/rerank/protenix/chembl_bdb/chembl_bdb_meta.lmdb
    meta_split: train_3w_100
    feat_lmdb_path:
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_1.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_2.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_3.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_4.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_5.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_6.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/pair/sample_3w_pair_7.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_1.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_2.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_3.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_4.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_5.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_6.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_val_3w/pair/sample_val_pair_7.lmdb
    feat_split: full_pair
    include_screen: true
    max_screen: null
    include_rerank: true
    max_rerank: null
  val:
    _target_: protenix.data.pair_dataset.FullPairDataset
    meta_path: /data/rerank/protenix/chembl_bdb/chembl_bdb_meta.lmdb
    meta_split: val_5k
    feat_lmdb_path:
      - /data/rerank/protenix/chembl_bdb/sample_val/sample_val_pair.lmdb
    feat_split: full_pair