_target_: protenix.data.pair_dataset.DataModule
num_workers: 16
pin_memory: True
batch_size: 32
prefetch_factor: 2
dataset_args:
  train:
    _target_: protenix.data.pair_dataset.FullTripletDataset
    meta_path: /data/rerank/protenix/chembl_bdb/chembl_bdb_meta.lmdb
    meta_split: train_3w
    feat_lmdb_path:
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_1.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_2.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_3.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_4.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_5.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_6.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_7.lmdb
      - /data/rerank/protenix/chembl_bdb/sample_3w/triplet_v2/block_8.lmdb
    feat_split: full_triplet
    include_screen: true
    max_screen: null
    include_rerank: true
    max_rerank: null
  val:
    _target_: protenix.data.pair_dataset.FullTripletDataset
    meta_path: /data/rerank/protenix/chembl_bdb/chembl_bdb_meta.lmdb
    meta_split: val_5k
    feat_lmdb_path:
      - /data/rerank/protenix/chembl_bdb/sample_val/sample_val_triplet_v2.lmdb
    feat_split: full_triplet